# Start with the Node.js base image
FROM oven/bun:alpine as base
FROM node:18-alpine3.18

# Copy Bun from the oven/bun image
COPY --from=base /usr/local/bin/bun /usr/local/bin/bun

# Add your user and group, if needed
RUN groupadd bun \
  --gid 1000 \
  && useradd bun \
  --uid 1000 \
  --gid bun \
  --shell /bin/sh \
  --create-home \
  && ln -s /usr/local/bin/bun /usr/local/bin/bunx \
  && which bun \
  && which bunx \
  && bun --version

# Set the working directory
WORKDIR /home/bun/app

# Copy any additional files, such as your entrypoint script
COPY docker-entrypoint.sh /usr/local/bin

# Set the entrypoint and default command
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["/usr/local/bin/bun"]
