# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '33 22 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "👋 Hey there! It looks like this issue hasn't seen any activity in the last 60 days. We understand projects evolve and priorities shift. If this topic is still pressing for you, please feel free to refresh the conversation by removing the 'stale' label or adding a new comment. On the flip side, if no action is taken, this issue will automatically close in 7 days. Our community thrives on collaboration, and with thousands of active users monthly, there's a good chance someone has insights or solutions to offer. If this issue is critical to your work, we encourage you to take the lead—whether that's submitting a pull request yourself or seeking external assistance. Rest assured, we're here to support your contributions and will expedite reviews and merges to keep the momentum going. Your active participation is key to our collective success. Thanks for being a vital part of our community. Let's keep pushing the envelope, together! 🚀"
        stale-pr-message: "👋 Hello! We've noticed this pull request has been inactive for the past 60 days. In the dynamic world of development, we understand that priorities can shift, and sometimes things get put on hold. If you're still working on this, or if it's ready for another review, please update the PR or leave a comment to keep it active. Without further activity, this PR will be marked as stale in 7 days and may be closed if no further action is taken. Our project thrives on contributions from our community, and we're eager to see your work integrated! If you need assistance or have questions, don't hesitate to reach out. Your initiative could be exactly what we need to enhance our project. Let's collaborate to keep our momentum going and make impactful progress. Thank you for your contributions and for being an essential part of our community! 🚀"
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
